Allow password change without mfa by enabling iam:GetLoginProfile
trussworks/terraform-aws-mfa pull request #44
Opened 2020-10-09 22:11 UTC by chrisgilmerproj

Users without an MFA who have just received an account with password access (not access keys) may need to change their password on first login. Unfortunately the policy doesn't allow them to see their LoginProfile and modify the password. By adding `iam:GetLoginProfile` to the set of actions that are still available without an MFA enabled we can allow folks to modify their password BEFORE having the MFA in place.

2020-10-23 19:59 UTC, chrisgilmerproj commented
@eeeady - wanted to follow up on this and see if you had any questions.

2020-12-05 01:03 UTC, dynamike requested changes
I think this is a case were we are being a bit to permissive on access. Per the AWS the AWS docs which is where this module came from 
> This example policy does not allow users to reset their password while signing in. New users and users with an expired password might try to do so. You can allow this by adding iam:ChangePassword and iam:CreateLoginProfile to the statement BlockMostAccessUnlessSignedInWithMFA. However, IAM does not recommend this.

https://docs.aws.amazon.com/global-accelerator/latest/dg/auth_access_overview.html

Which would mean taking out `iam:CreateLoginProfile` and `iam:ChangePassword`

2020-12-05 04:15 UTC, chrisgilmerproj commented
You're right, they go together. You should have either both or none. Since you're attempting to model after the AWS docs here I'm just going to close this out.

2020-12-05 04:15 UTC, closed without merging

2020-12-07 18:41 UTC, chrisgilmerproj commented
As a follow up I'm experimenting with this module: https://github.com/dod-iac/terraform-aws-self-manage-credentials

Also, it appears that you need to release a new version so folks can use commit https://github.com/trussworks/terraform-aws-mfa/commit/0d10e4fbd43fc61d13db44d623c37d9089e60eee